name: CI

on:
  push:
    branches: [ main ]

jobs:  
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'

      - name: Install dependencies
        run: go mod tidy

      - name: Build project
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.3'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v -race ./tests/...